### ISSUE TITLE
will this be maintained ? (since it's not in redis python) 

### ISSUE THREAD

**Issue by ishaan-jaff** [RedisVentures/redisvl#111]
I love this package so far, we're adding it to https://github.com/BerriAI/litellm. I want to make sure this package will be maintained for the next year? 

(asking because it's not part of the redis python lib)

**Comment by tylerhutcherson** [comment]
Yes this library will be maintained! All ecosystem integrations will be switched over to use this library as the preferred route. It's meant to be interoperable with the base python client too.
