### ISSUE TITLE
[Feat] Add index.ping() 

### ISSUE THREAD

**Issue by ishaan-jaff** [RedisVentures/redisvl#113]
After initializing an index() I need to know if it was created successfully, Can you expose something like this ?

**Comment by tylerhutcherson** [comment]
Hi @ishaan-jaff -- Does `index.exists()` or `index.info()` suffice for your use case? Can you share a bit more details?

**Comment by ishaan-jaff** [comment]
use case - users start the litellm server, I need them to know if the redis index is healthy/was created successfully 

I think index.exists() would work - will try this

**Comment by ishaan-jaff** [comment]
works -  thanks !
