### ISSUE TITLE
Switch to poetry for package management

### ISSUE THREAD

**Issue by tylerhutcherson** [RedisVentures/redisvl#130]

**Comment by bsbodden** [comment]
@tylerhutcherson I can take a stab at this one if you haven't done it already

**Comment by tylerhutcherson** [comment]
For example, want to be able to do :
```
poetry install --with dev,docs
```

**Comment by tylerhutcherson** [comment]
Completed and now released as part of 0.2.0
https://github.com/RedisVentures/redisvl
