### ISSUE TITLE
Build better conditional filter expression interface

### ISSUE THREAD

**Issue by tylerhutcherson** [RedisVentures/redisvl#71]
Currently, using redisvl  there is a pattern emerging from the FilterExpression  usage. Functions like the following are commonly being written by end users.
```python
def build_filter_expression(years: List[int], categories: List[str]) -> FilterExpression:
    """
    Construct a filter expression based on the provided years and categories.
    Args:
        years (list): A list of years (integers or strings) to be included in the filter
                      expression. An empty list means there's no filter applied based on years.
        categories (list): A list of category strings to be included in the filter
                           expression. An empty list means there's no filter applied based
                           on categories.
    Returns:
        FilterExpression: A FilterExpression object representing the combined filter for both years and categories.
    """
    # Build filters
    year_filter = Tag("year") == [str(year) for year in years] if years else None
    category_filter = Tag("categories") == [str(category) for category in categories] if categories else None
    # Parse and create filter expression
    if not year_filter and not category_filter:
        return FilterExpression("*")
    if year_filter and category_filter:
        return year_filter & category_filter
    return year_filter or category_filter
```
This function is verbose and there are two specific problems

the presence of conditional values i.e. None 
Chaining given the presence of conditionals

Deliverable:
Design and implement and approach that allows for a conditional value to be passed
Ensure that if None  is passed, the following chaining operation is not effected.

example, the function should be able to look like.
```python
def build_filter_expression(years: List[int], categories: List[str]) -> FilterExpression:
    """
    Construct a filter expression based on the provided years and categories.
    Args:
        years (list): A list of years (integers or strings) to be included in the filter
                      expression. An empty list means there's no filter applied based on years.
        categories (list): A list of category strings to be included in the filter
                           expression. An empty list means there's no filter applied based
                           on categories.
    Returns:
        FilterExpression: A FilterExpression object representing the combined filter for both years and categories.
    """
    # Build filters
    year_filter = Tag("year") == [str(year) for year in years]
    category_filter = Tag("categories") == [str(category) for category in categories]
    return year_filter & category_filter
```

AC:
Implement this capability with tests and examples in the notebooks.

**Comment by tylerhutcherson** [comment]
Design Considerations / Notes -- 

- It is possible for us to have scenarios where a single FilterExpression should yield essentially "no filter". **In otherwords `*` in the redis query language.**
    -  For Tags  -- in the example above, if the list of `years` or `categories` is empty or None, then we are to say that the filter is essentially "invalid" and should be ignored from expressions.
    - For Text?? For Numbers?? Nothing immediately unique stands out beyond improperly defined filters, which seems like a separate issue.


To make this interface better we need to address two things:
- Be able to handle an individual filter type that should actually resolve to `*`
- Be able to handling combining filters that involve `*` from ^

**Comment by Spartee** [comment]
Done in #72
