### ISSUE TITLE
Unable to pass redis client when loading existing index

### ISSUE THREAD

**Issue by bibinbalakrishnan** [RedisVentures/redisvl#79]
When loading an existing index, get_redis_connection method in connection.py should allow passing of an existing redis client instance as well

for example :
index = SearchIndex.from_dict(schema)
index.set_client(redis)

works

But, this won’t work for SerachIndex.from_existing

This prevents users from passing redis connection objects created outside to be passed into while loading an existing index

**Comment by Spartee** [comment]
@bibinbalakrishnan this is a good point. We can make that change. We're about to cut 0.0.5, but this can make it into the next release. It'll be on main shortly.

**Comment by tylerhutcherson** [comment]
For now, we are deprecating `from_existing` as it causes too many issues for this layer in the client architecture and there's not enough need for this yet. Higher level clients like LangChain and LlamaIndex will retain similar patterns. For redisvl, all you have to do is provide your schema to the client and it will continue to work!
