### ISSUE TITLE
Update to Pydantic >2.0.0

### ISSUE THREAD

**Issue by irradiantlife** [RedisVentures/redisvl#86]
Update to Pydantic 2.0+

I took a look at patching it.
This project's @validator is easily updated to @field_validator.
There is a breaking unit test: tests/integration/test_llmcache.py that I was not able to resolve.

**Comment by Spartee** [comment]
Hi @irradiantlife thanks for the issue. we actually had Pydantic 2.0 but it was breaking some use cases where people would use RedisVL with Langchain. Now that Langchain is compatible with 2.0, we should look at putting that back in.

**Comment by wenboown** [comment]
Thank you for the great work! Redisvl helps me a lot in my projects, and getting it back to Pydantic 2.0 will help making this compatible with a lot of other packages. 👍

**Comment by tylerhutcherson** [comment]
Another ++ for this @Spartee from a conversation I had online today with a user.

**Comment by tylerhutcherson** [comment]
Addressed in https://github.com/RedisVentures/redisvl/pull/101
